# 索引、切片与迭代

In [1]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
y = x
y[0] = -1
print(x)
print(y)

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x.copy()
y[0] = -1
print(x)
print(y)

[-1  2  3  4  5  6  7  8]
[-1  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]
[-1  2  3  4  5  6  7  8]
